### ISSUE TITLE
AS3.0出现生成AndroidManifest文件包名出错

### ISSUE THREAD

**Issue by codesdt** [JessYanCoding/MVPArmsTemplate#1]
我卸载AS后，全新的安装AS3.0,下载AS依赖的信息，直到项目能够正常运行，然后下载MVPArmsTemplate插件解压，复制
![image](https://user-images.githubusercontent.com/12639114/32131904-f96f5762-bb7e-11e7-9b58-c5a74aff5572.png)
这个文件到
![image](https://user-images.githubusercontent.com/12639114/32131909-05a3434a-bb7f-11e7-8346-62ded2ec958e.png)
![image](https://user-images.githubusercontent.com/12639114/32131913-11b93360-bb7f-11e7-93d2-3f88ba2ce7df.png)
然后按照教程新建一个类后，
![image](https://user-images.githubusercontent.com/12639114/32131918-2292e816-bb7f-11e7-9380-6e459981c916.png)
包名缺少路径，其他新建类一切正常，请问是怎么回事？

**Comment by JessYanCoding** [comment]
Fixed and close the issues https://github.com/JessYanCoding/MVPArmsTemplate/commit/7ab1bd8dd883008ff470fe76ed39e1282f0802d4
