### ISSUE TITLE
全家桶报错了

### ISSUE THREAD

**Issue by panrongfu** [JessYanCoding/MVPArmsTemplate#12]
Error executing FreeMarker template: The following has evaluated to null or missing:
==> ktOrJavaExt  [in template "root://activities/MVPArmsTemplate/recipe.xml.ftl" at line 22, column 60]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction:
==> ${ktOrJavaExt}  [in template "root://activities/MVPArmsTemplate/recipe.xml.ftl" at line 22, column 58]
FreeMarker template error:
The following has evaluated to null or missing:
==> ktOrJavaExt  [in template "root://activities/MVPArmsTemplate/recipe.xml.ftl" at line 22, column 60]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (FTL stack trace):
----------
==> ${ktOrJavaExt}  [in template "root://activities/MVPArmsTemplate/recipe.xml.ftl" at line 22, column 58]
----------

Java stack trace (for programmers):

**Comment by panrongfu** [comment]
我的是3.0的

**Comment by q232916067** [comment]
我的3.2的也是报错

**Comment by q232916067** [comment]
rror executing FreeMarker template: Error reading included file "root://gradle-projects/MVPArmsTemplate/../common/common_globals.xml.ftl":
Template "root://gradle-projects/MVPArmsTemplate/../common/common_globals.xml.ftl" not found.

The failing instruction:
==> #include "../common/common_globals.xm...  [in template "root://gradle-projects/MVPArmsTemplate/globals.xml.ftl" at line 10, column 5]
FreeMarker template error:
Error reading included file "root://gradle-projects/MVPArmsTemplate/../common/common_globals.xml.ftl":
Template "root://gradle-projects/MVPArmsTemplate/../common/common_globals.xml.ftl" not found.

The failing instruction (FTL stack trace):
----------
==> #include "../common/common_globals.xm...  [in template "root://gradle-projects/MVPArmsTemplate/globals.xml.ftl" at line 10, column 5]
----------

**Comment by q232916067** [comment]
我知道原因了 因为拷贝错了文件夹 那两个文件夹不一样的

**Comment by JessYanCoding** [comment]
@panrongfu 升级到 AS 最新版
