### ISSUE TITLE
更新template了

### ISSUE THREAD

**Issue by 1325679717** [JessYanCoding/MVPArmsTemplate#16]
大神template该更新了，最新as3.4.2

**Comment by JessYanCoding** [comment]
现在的模板是支持as3.4.2，不需要更新

**Comment by suziqiang** [comment]
你好大神 我的studio3.4.2没反应不能识别出全家桶  路径位置没问题 As也重启了

**Comment by 1325679717** [comment]
好的 感谢

**Comment by 1325679717** [comment]
> 大神template该更新了，最新as3.4.2
好的 感谢

**Comment by zhouxiaoli521** [comment]
现在模板里用的还是老版的包名 
![image](https://user-images.githubusercontent.com/534263/64482041-46305280-d21c-11e9-8760-929c2042e4bd.png)

**Comment by JessYanCoding** [comment]
@zhouxiaoli521 你这用的是 MVPArt 的模板，不是 MVPArms 的
