### ISSUE TITLE
as 3.5新建mvparms编译一大堆错误。从新建demo,运行demo成功，加入module也成功，去除androidx的android.useAndroidX=true android.enableJetifier=true也成功。到这一步都是可以运行的，新建activity模板时错误

### ISSUE THREAD

**Issue by vance0901** [JessYanCoding/MVPArmsTemplate#21]
编译错误（摘取一段编译错误源码）
D:\user\app\src\main\java\com\zhuzu\user\mvp\ui\fragment\MainFragment.java:47: 错误: 找不到符号
        DaggerMainComponent //如找不到该类,请编译一下项目
        ^
  符号:   变量 DaggerMainComponent
  位置: 类 MainFragment
D:\user\app\src\main\java\com\zhuzu\user\mvp\ui\fragment\MainFragment.java:55: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
100 个错误

怎么回事。

**Comment by JessYanCoding** [comment]
dagger 错误，是你自己不熟悉 dagger 规则引起的，和框架没什么关系，dagger 报错只看最后一个错误，不要管前面的
