### ISSUE TITLE
Android studio3.6

### ISSUE THREAD

**Issue by WiseDiligent** [JessYanCoding/MVPArmsTemplate#24]
Android studio3.6 版本不支持？？？  能不能做下适配

**Comment by JessYanCoding** [comment]
Android studio 3.5.3 没问题哇

**Comment by WiseDiligent** [comment]
> Android studio 3.5.3 没问题哇

是的，但是我升级3.6之后，就有问题，生成不了MVP加个了， 你升级到3.6 试试

**Comment by JessYanCoding** [comment]
```
FreeMarker template error:
The following has evaluated to null or missing:
==> isNewProject  [in template "root://activities/MVPArmsTemplate/dagger2_macros.ftl" at line 2, column 9]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (FTL stack trace):
----------
==> #if !isNewProject && ((language!"Java...  [in template "root://activities/MVPArmsTemplate/dagger2_macros.ftl" in macro "addAllKaptDependencies" at line 2, column 3]
    @dagger2.addAllKaptDependencies  [in template "root://activities/MVPArmsTemplate/recipe.xml.ftl" at line 6, column 1]
----------
```
这个错误哇

**Comment by WiseDiligent** [comment]
> ```
> FreeMarker template error:
> The following has evaluated to null or missing:
> ==> isNewProject  [in template "root://activities/MVPArmsTemplate/dagger2_macros.ftl" at line 2, column 9]
> 
> Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??
> 
> The failing instruction (FTL stack trace):
> ----------
> ==> #if !isNewProject && ((language!"Java...  [in template "root://activities/MVPArmsTemplate/dagger2_macros.ftl" in macro "addAllKaptDependencies" at line 2, column 3]
>     @dagger2.addAllKaptDependencies  [in template "root://activities/MVPArmsTemplate/recipe.xml.ftl" at line 6, column 1]
> ----------
> ```
> 
> 这个错误哇

控制台没有看到错误提示哈哈 ，不好意思，

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/MVPArmsTemplate/commit/b01170d073227276106ded23c7c908e2ca618953

好了

**Comment by WiseDiligent** [comment]
ok，  谢谢

**Comment by zhangguannan** [comment]
下载的最新版本  还是在报这个错  也是Android studio3.6用的是arms
